[loggers]
keys=root, arq_logger, init_logger

[handlers]
keys=logfile, logconsole, arqFileHandler, initFileHandler

[formatters]
keys=logformatter

[logger_root]
level=INFO
handlers=logfile, logconsole

[logger_arq_logger]
level=INFO
handlers=arqFileHandler
qualname=arq_logger
propagate=0

[formatter_logformatter]
format=[%(asctime)s.%(msecs)03d] %(levelname)s [%(thread)d] - %(message)s

[handler_logfile]
class=handlers.RotatingFileHandler
level=INFO
args=('logfile.log', 'a', 10485760, 5, 'utf-8')  # Added encoding='utf-8'
formatter=logformatter

[handler_logconsole]
class=handlers.logging.StreamHandler
level=INFO
args=()
formatter=logformatter

[handler_arqFileHandler]
class=handlers.RotatingFileHandler
level=INFO
args=('arc_log.log', 'a', 10485760, 5, 'utf-8')  # Added encoding='utf-8'
formatter=logformatter

[logger_init_logger]
level=INFO
handlers=initFileHandler
qualname=init_logger
propagate=0

[handler_initFileHandler]
class=logging.handlers.RotatingFileHandler
level=INFO
formatter=logformatter
args=('init_collections.log', 'a', 10485760, 5)
encoding=utf-8


#used to configure Python logging,
#lets you define log level, log format, handlers, and destinations (files, console, etc.)
#This tells Python: create a console handler, use INFO level, format log lines with timestamps and message text